### ISSUE TITLE
Filter progress chart by exercise

### ISSUE THREAD

**Issue by rrrhys** [victorparmar/easy-workout-log#3]
Hi, Ewolo is great :)

The dashboard chart is a little hard to view progress on, because all types of workouts are aggregated.

![image](https://user-images.githubusercontent.com/361922/28752803-62294a24-756b-11e7-808a-edef27fff4a1.png)

In the image above, today I did barbell press (lower weight, many more reps) and yesterday I did squats (higher weight, many less reps). The chart compares them by outright kg.

If a dropdown box allowed filtering by workout type, like (screenshot below), then the dashboard graph would be great to plot progress.

![image](https://user-images.githubusercontent.com/361922/28752821-a74b1fa6-756b-11e7-87a8-3ae255fbc2a4.png)

**Comment by victorparmar** [comment]
Hi Rhys,

Thanks for filing this issue. I also wanted to streamline the dashboard and
provide customizable charts :)

This will definitely come soon. I'll keep you posted, cheers!

**Comment by victorparmar** [comment]
Hi Rhys,

The latest release of Ewolo now incorporates filters for the dashboard progress chart.

There also a dedicated analysis section in the pipeline where you would see charts for individual exercises with their 1RM, 5RM and so on.

I hope you are still finding Ewolo useful and do keep me posted if you have any other ideas for improvement.

Cheers!

On 30-07-17, Rhys Williams wrote:
> Hi, Ewolo is great :)
> 
> The dashboard chart is a little hard to view progress on, because all types of workouts are aggregated.
> 
> ![image](https://user-images.githubusercontent.com/361922/28752803-62294a24-756b-11e7-808a-edef27fff4a1.png)
> 
> In the image above, today I did barbell press (lower weight, many more reps) and yesterday I did squats (higher weight, many less reps). The chart compares them by outright kg.
> 
> If a dropdown box allowed filtering by workout type, like (screenshot below), then the dashboard graph would be great to plot progress.
> 
> ![image](https://user-images.githubusercontent.com/361922/28752821-a74b1fa6-756b-11e7-87a8-3ae255fbc2a4.png)
> 
> 
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/victorparmar/easy-workout-log/issues/3

-- 

Victor Parmar
https://smalldata.tech
